# -*- coding: utf-8 -*-
"""ADVANCED CUSTOMER FEEDBACK ANALYSIS (TextBlob vs VADER vs BERT).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qry2zHLlf4rpu5F_TqF3w5p7nkleU_5j
"""

!pip install nltk textblob transformers torch pandas matplotlib seaborn wordcloud

# ADVANCED CUSTOMER FEEDBACK ANALYSIS (TextBlob vs VADER vs BERT)
# Import libraries
import pandas as pd
import nltk
from textblob import TextBlob
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import re

# Download NLTK stopwords (for cleaning)
nltk.download('stopwords')
nltk.download('vader_lexicon')


# Upload your feedback CSV file
uploaded = files.upload()

# Load the file
file_name = list(uploaded.keys())[0]
df = pd.read_csv(file_name, encoding='latin1')
df.head()

df.rename(columns={
    'Review Title':'review_title',
    'Customer name':'customer_name',
    'Rating':'rating',
    'Date':'date',
    'Category':'category',
    'Comments':'comments',
    'Useful':'useful'
}, inplace=True)

def clean_text(t):
    t = str(t).lower()
    t = re.sub(r'[^a-z\s]', '', t)
    return t

df['clean_comments'] = df['comments'].apply(clean_text)

# 1. TextBlob Sentiment
def textblob_sentiment(t):
    score = TextBlob(t).sentiment.polarity
    if score > 0.05:
        return "positive"
    elif score < -0.05:
        return "negative"
    return "neutral"

df['textblob_sentiment'] = df['clean_comments'].apply(textblob_sentiment)

# 2. VADER Sentiment
sia = SentimentIntensityAnalyzer()

def vader_sentiment(t):
    score = sia.polarity_scores(t)['compound']
    if score > 0.05:
        return 'positive'
    elif score < -0.05:
        return 'negative'
    return 'neutral'

df['vader_sentiment'] = df['comments'].astype(str).apply(vader_sentiment)

# 3. BERT Sentiment
tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment-latest")
model = AutoModelForSequenceClassification.from_pretrained("cardiffnlp/twitter-roberta-base-sentiment-latest")

labels = ["negative", "neutral", "positive"]

def bert_sentiment(t):
    # Add max_length to explicitly truncate long sequences to 512 tokens
    inputs = tokenizer(t, return_tensors="pt", truncation=True, max_length=512)
    outputs = model(**inputs)
    score = torch.softmax(outputs.logits, dim=1)
    return labels[torch.argmax(score)]

df['bert_sentiment'] = df['comments'].astype(str).apply(bert_sentiment)

#Grouped Bar Chart — TextBlob vs VADER vs BERT Shows how all three models compare on sentiment counts.
import matplotlib.pyplot as plt
import pandas as pd

model_counts = pd.DataFrame({
    "TextBlob": df['textblob_sentiment'].value_counts(),
    "VADER": df['vader_sentiment'].value_counts(),
    "BERT": df['bert_sentiment'].value_counts()
}).fillna(0)

model_counts.plot(kind='bar', figsize=(10,6))
plt.title("Sentiment Comparison: TextBlob vs VADER vs BERT")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.xticks(rotation=0)
plt.show()

plt.figure(figsize=(14,5))

plt.subplot(1,3,1)
df['textblob_sentiment'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("TextBlob")

plt.subplot(1,3,2)
df['vader_sentiment'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("VADER")

plt.subplot(1,3,3)
df['bert_sentiment'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("BERT")

plt.tight_layout()
plt.show()

#Positive
pos_text = " ".join(df[df['bert_sentiment']=='positive']['clean_comments'])
wc = WordCloud(width=800, height=400, background_color='white').generate(pos_text)
plt.figure(figsize=(10,5))
plt.imshow(wc)
plt.axis('off')
plt.title("Positive WordCloud (BERT)")
plt.show()

#Negative
neg_text = " ".join(df[df['bert_sentiment']=='negative']['clean_comments'])
wc = WordCloud(width=800, height=400, background_color='white').generate(neg_text)
plt.figure(figsize=(10,5))
plt.imshow(wc)
plt.axis('off')
plt.title("Negative WordCloud (BERT)")
plt.show()

#If someone wants to test a single sentence:
def analyze_sentence(sentence):
    tb = textblob_sentiment(sentence)
    vd = vader_sentiment(sentence)
    br = bert_sentiment(sentence)
    print(f"Sentence: {sentence}")
    print(f"TextBlob: {tb}, VADER: {vd}, BERT: {br}")

# Example
analyze_sentence("I love this product!")